{{ range $.Values.testJSON }}
#JSON:{{- . }}
apiVersion: v1
kind: Pod
metadata:
  name: pod-{{- .name }}
  labels:
    app: pod-{{- .name }}
  {{- if .labels }}
  {{- range .labels }}
    {{ . }}: label-{{ . }}
  {{- end }}
  {{- end }}
  {{- with .type }}
  annotations:
    type: {{ . }}
  {{- end }}
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - name: http
        containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-pod-{{- .name }}
spec:
  type: ClusterIP
  selector:
    app: pod-{{- .name }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
---
{{ end }}